### ISSUE TITLE
Build instruction don't work in Ubuntu

### ISSUE THREAD

**Issue by spoetnik** [goalgorilla/drupal_social#115]
I tried to build the docker environment on Ubuntu, but this doesn't work. The mounts to the 'drupalsocial_web' container aren't available.

Couldn't find a solution yet, if I find out, I wil post it here.

**Comment by spoetnik** [comment]
Never mind. Why use a VM when running Linux. 
    docker build . 
works.

**Comment by illepic** [comment]
@spoetnik can you clarify a bit here: I'm on Ubuntu, so I still need to create a docker-machine using the Virtualbox driver?

**Comment by spoetnik** [comment]
@illepic no, docker-machine is only needed for osx and Windows. Just install Docker, and docker-compose and you are good to go!

**Comment by illepic** [comment]
Cheers, thanks!
