### ISSUE TITLE
Slow performance...

### ISSUE THREAD

**Issue by spoetnik** [goalgorilla/drupal_social#117]
The default boot2docker uses vboxsf mounted folders and these are way slower compared to nfs.
Using https://github.com/adlogix/docker-machine-nfs sped up the performance of the mounts enormous. From unworkable, to reasonable fast.

**Comment by NielsGG** [comment]
Hi @spoetnik,

Thanks for the advice. We currently do not experience slow performance using our Macbooks with the default Docker Machine but we know that using NFS brings a significant improvement.

In my opinion it is very important that new developers can get an environment up and running as soon as possible with a very friendly user experience that the Docker Toolbox installation provides. Maybe we should add a FAQ section in the wiki that clusters solutions like this in case the performance is too slow.

Greetings,

Niels

**Comment by NielsGG** [comment]
For reference, it seems that Docker is working on a solution which is currently in private beta:
https://blog.docker.com/2016/03/docker-for-mac-windows-beta/

Also another option I heard about is DINGHY with a similar shell as docker-machine-nfs.
https://github.com/codekitchen/dinghy

**Comment by spoetnik** [comment]
I think we saw the same session at DrupalJam ;-)
Disadvantage of dinghy is new cli-tool, where the docker-machine-nfs script adjust your boot2docker vm. A matter of preference I think, but I like to just use the docker-machine cli.

**Comment by NielsGG** [comment]
Tried out docker-machine-nfs and it works pretty well so far. Created a wiki page to set it up.
https://github.com/goalgorilla/drupal_social/wiki/How-to-speed-up-local-development-on-OSX-using-docker-machine-nfs
