### ISSUE TITLE
Access to the Roadmap

### ISSUE THREAD

**Issue by luxio** [goalgorilla/drupal_social#167]
Is it possible to get access to the [Roadmap](https://drupalsocial.storiesonboard.com/m/drupal-social-mvp)

**Comment by jaapjan** [comment]
I see the URL is incorrect in the readme. I will change it.

This should be the correct URL and you should have access as well: https://drupalsocial.storiesonboard.com/m/open-social

Kind regards,
Jaap Jan Koster

**Comment by luxio** [comment]
Thanks
