### ISSUE TITLE
Docker instructions: /root/dev-scripts/install/install_script.sh: No such file or directory

### ISSUE THREAD

**Issue by illepic** [goalgorilla/drupal_social#214]
The current Readme.md docker instructions state to run:

    docker exec -it social_web_1 bash /root/dev-scripts/install/install_script.sh

A quick `docker-compose ps` indicates that my web container is called `drupalsocial_web_1`:

````bash
           Name                         Command               State                        Ports                       
----------------------------------------------------------------------------------------------------------------------
drupalsocial_cron_1          /bin/sh -c cron && tail -f ...   Up      80/tcp                                           
drupalsocial_db_1            docker-entrypoint.sh mysqld      Up      0.0.0.0:3307->3306/tcp                           
drupalsocial_mailcatcher_1   mailcatcher -f --ip=0.0.0.0      Up      1025/tcp, 0.0.0.0:32768->1080/tcp                
drupalsocial_web_1           apache2-foreground               Up      0.0.0.0:32769->80/tcp                            
social_behat                 apache2-foreground               Up      80/tcp                                           
social_selenium              /opt/bin/entry_point.sh          Up      0.0.0.0:32771->4444/tcp, 0.0.0.0:32770->5900/tcp
````

So modifying the suggested command to:

    docker exec -it drupalsocial_web_1 bash /root/dev-scripts/install/install_script.sh

Results in the output:

````
> $ docker exec -it drupalsocial_web_1 bash /root/dev-scripts/install/install_script.sh
bash: /root/dev-scripts/install/install_script.sh: No such file or directory
````

**Comment by illepic** [comment]
Ah, the volumes did not mount. I have Vagrant currently running for another project nearby, would that cause issues?

**Comment by NielsGG** [comment]
hi @illepic,

It is likely that the project is not inside your users directory which it should be in order to mount the volumes. The other vagrant projects should not be an issue unless you use docker with NFS (which is not enabled by default).

**Comment by illepic** [comment]
Ah, I should note that I'm on Ubuntu 16.04 here, working from `~/dev/drupal_social` (`/home/illepic/dev/drupal_social`). Any thoughts on issues there?

**Comment by illepic** [comment]
Still learning the ropes with Docker, this might lead to my solution: https://github.com/goalgorilla/drupal_social/issues/115

**Comment by NielsGG** [comment]
No experience with Ubuntu, what version of Docker and Docker Compose are you running? You can also check some more mount information with `docker inspect drupalsocial_web_1`. The relevant information should be under the mounts area.

**Comment by illepic** [comment]
The mount information is there, the host is just not playing nice it appears:

````shell
"Mounts": [
            {
                "Source": "/home/illepic/dev/drupal_social/dev-scripts",
                "Destination": "/root/dev-scripts",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/home/illepic/dev/drupal_social/public_html",
                "Destination": "/var/www/html",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
````

**Comment by NielsGG** [comment]
Hi @illepic,

Mounts are looking good, did you resolve the issue? This docker-compose issue seems to discuss the same problem https://github.com/docker/compose/issues/2247. You can try to install a specific version of docker-compose that we know works on our CI system.

Here are the steps that we use in our travis.yml file to install docker-compose 1.6.2:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.6.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
