### ISSUE TITLE
Error editing profile after new registration

### ISSUE THREAD

**Issue by kreativmind** [goalgorilla/drupal_social#287]
I created a test user on my site. After successfully registering and confirming the email, I click on the pencil icon to edit profile and fill in the details. When I click Save, it brings me to page mysite.com/user/3/profile and displays the following message on a blank white space page:
The website encountered an unexpected error. Please try again later.

Also, I am not sure why it skipped to user 3 when I only have admin account and the test account I created, so it should be user/2/profile, correct?

Any ideas?

**Comment by ronaldtebrake** [comment]
See for an answer: https://github.com/goalgorilla/open_social/issues/11
