### ISSUE TITLE
An update to the Install page

### ISSUE THREAD

**Issue by marqpdx** [goalgorilla/drupal_social#289]
hi,

it seems that on the install page, we need to change from this:
`sh docker_build/drupal8/install_script.sh`
to
`docker-compose exec web bash /root/dev-scripts/install/install_script.sh`

Section 1.2.2.7 here: https://github.com/goalgorilla/drupal_social/wiki/Installing-and-updating

Thanks,
m

ps, this might apply as well: https://www.drupal.org/node/2690519
pps, do you accept pull requests for the Wiki pages?

**Comment by ronaldtebrake** [comment]
Hi,

Thanks a lot, i've updated the wiki.

Unfortunately docker-compose only works with version 1.7 +.  But as you noticed in the link you mentioned

`docker exec social_web bash /root/dev-scripts/install/install_script.sh` 

Should work for everybody.

Regarding pull requests for wiki pages, we haven't set it up as a separate repository (yet). Definitely something we can look in to in the future. 

Thanks,

Ronald
