### ISSUE TITLE
error on adding user

### ISSUE THREAD

**Issue by RudyMartin** [goalgorilla/drupal_social#294]
Location    http://test-social1609.pantheonsite.io/admin/people/create
Referrer    http://test-social1609.pantheonsite.io/search/user
Message Symfony\Component\Routing\Exception\InvalidParameterException: Parameter "selection_handler" for route "system.entity_autocomplete" must match "[^/]++" ("" given) to generate a corresponding URL. in Drupal\Core\Routing\UrlGenerator->doGenerate() (line 193 of /srv/bindings/f622836bde6b407eacb77d0ff7ec70f6/code/core/lib/Drupal/Core/Routing/UrlGenerator.php).

**Comment by ronaldtebrake** [comment]
Hi there,

Hopefully by now you've been able to install Open Social
For installing on Pantheon we have a repo here: https://github.com/lquessenberry/OpenSocialOnPantheon
