### ISSUE TITLE
error on creating group

### ISSUE THREAD

**Issue by RudyMartin** [goalgorilla/drupal_social#295]
Location    http://test-social1609.pantheonsite.io/group/add/open_group
Referrer    http://test-social1609.pantheonsite.io/group/add/open_group
Message Recoverable fatal error: Argument 1 passed to Drupal\Core\Form\FormState::setError() must be of the type array, null given, called in /srv/bindings/f622836bde6b407eacb77d0ff7ec70f6/code/core/lib/Drupal/Core/Field/WidgetBase.php on line 441 and defined in Drupal\Core\Form\FormState->setError() (line 1151 of /srv/bindings/f622836bde6b407eacb77d0ff7ec70f6/code/core/lib/Drupal/Core/Form/FormState.php).

**Comment by ronaldtebrake** [comment]
See #294
