### ISSUE TITLE
error on node add

### ISSUE THREAD

**Issue by RudyMartin** [goalgorilla/drupal_social#296]
Location    http://test-social1609.pantheonsite.io/node/8
Referrer    http://test-social1609.pantheonsite.io/node/add/article
Message User warning: The following theme is missing from the file system: social_search in drupal_get_filename() (line 234 of /srv/bindings/f622836bde6b407eacb77d0ff7ec70f6/code/core/includes/bootstrap.inc).

**Comment by ronaldtebrake** [comment]
See #294
