### ISSUE TITLE
warning after enabling Social activity feature module

### ISSUE THREAD

**Issue by RudyMartin** [goalgorilla/drupal_social#297]
Location    http://test-social1609.pantheonsite.io/
Referrer    http://test-social1609.pantheonsite.io/admin/modules
Message Warning: rename(sites/default/files/php/twig/.13a5450f4a,sites/default/files/php/twig/0ce3103a_pager.html.twig_48004d2f385455f7bcc3d26309587ae9a573c16c7c2bb7f125212fef4113cac3/e7ca65fccd79fb4094d32dc867bd52ae466420702767b1b4d8c85fdf4e2e7c47.php): No such file or directory in Drupal\Component\PhpStorage\MTimeProtectedFastFileStorage->save() (line 86 of /srv/bindings/f622836bde6b407eacb77d0ff7ec70f6/code/core/lib/Drupal/Component/PhpStorage/MTimeProtectedFastFileStorage.php).

**Comment by ronaldtebrake** [comment]
See #294
