### ISSUE TITLE
error on article add - Field field_message_context is unknown

### ISSUE THREAD

**Issue by RudyMartin** [goalgorilla/drupal_social#298]
Location    http://test-social1609.pantheonsite.io/node/add/article
Referrer    http://test-social1609.pantheonsite.io/node/add/article
Message Drupal\Core\Entity\EntityStorageException: Field field_message_context is unknown. in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 770 of /srv/bindings/f622836bde6b407eacb77d0ff7ec70f6/code/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).

**Comment by GH2703** [comment]
Same issue here when creating a user on Pantheon: .../en/admin/people/create

Drupal\Core\Entity\EntityStorageException: Field field_message_context is unknown. in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 770 of /srv/bindings/64d7bd3ebd124e1f9509632f55f9c19a/code/web/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).

Drupal core 8.2.3
Open Social 8.x-1.0-beta6

**Comment by GH2703** [comment]
Similar issue when creating a group: .../en/group/add/open_group

Drupal\Core\Entity\EntityStorageException: The "" plugin does not exist. in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 770 of /srv/bindings/64d7bd3ebd124e1f9509632f55f9c19a/code/web/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).

Php 7.0

**Comment by johnreytanquinco** [comment]
Im also getting the same error message:
`Drupal\Core\Entity\EntityStorageException: Field field_message_context is unknown. in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 805 of /opt/app-root/src/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).`

**Comment by magick93** [comment]
Same issue

**Comment by johnreytanquinco** [comment]
The conflict happens when the **message template example module** is enabled then opensocial is asking for required fields to be added in the message template.

Solve the error message below by adding the existing field in the message template.
`Drupal\Core\Entity\EntityStorageException: Field field_message_context is unknown...`

But now getting this line smilar to @GH2703 
```
Drupal\Core\Entity\EntityStorageException: The "" plugin does not exist. in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 805 of /opt/app-root/src/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).
```

**Comment by ronaldtebrake** [comment]
Closing this see #294 if you have any problems with installing feel free to open up an issue on [drupal.org/project/issues/social](https://www.drupal.org/project/issues/social)
