### ISSUE TITLE
Can't install - commerceguys/zone module required

### ISSUE THREAD

**Issue by twogunz** [goalgorilla/drupal_social#302]
Using composer to install address module (1.0) and dependencies (composer require "drupal/address ~1.0" --prefer dist), the commerceguys/zone folder in the vendor directory is created properly. But I cannot install open-social because I keep getting "The Address module requires the commerceguys/zone library; For more information check our readme." I'm stumped! Thanks for any help you can offer!

**Comment by jochemvn** [comment]
Hi @twogunz,
Please move this issue to the drupal.org issue queue. See: https://github.com/goalgorilla/drupal_social/wiki/Support for more information.
Jochem

**Comment by twogunz** [comment]
Oops! My apologies. Will do so...
