### ISSUE TITLE
Install script moved in docker container

### ISSUE THREAD

**Issue by spoetnik** [goalgorilla/drupal_social#303]
After the merge from the 'extended-dev' the install script is not available to the docker container 'web'

So the installation instructions in the Wiki do not reflect the changes made in the merge
https://github.com/goalgorilla/drupal_social/wiki/Installing-and-updating

The correct path should be:

    docker exec social_web bash /var/www/dev-scripts/install/install_script.sh

**Comment by jaapjan** [comment]
Hi Martijn,

Thanks for the heads-up! Just changed it in the Wiki and also changed some other Wiki pages (hope I didn't miss anything this time!
