### ISSUE TITLE
Add http://portainer.io/ to dev environment

### ISSUE THREAD

**Issue by spoetnik** [goalgorilla/drupal_social#304]
http://portainer.io/ 
"PORTAINER IS AN OPEN-SOURCE LIGHTWEIGHT MANAGEMENT UI WHICH ALLOWS YOU TO EASILY MANAGE YOUR DOCKER HOST OR SWARM CLUSTER"

Easy to add to the docker-compose I think.

**Comment by ronaldtebrake** [comment]
Thanks for bringing it to our attention, we won't be adding this to our docker compose but you can always fork this repo and add all the cool docker things you want :)
