### ISSUE TITLE
Use Fewer Layers for docker build

### ISSUE THREAD

**Issue by spoetnik** [goalgorilla/drupal_social#306]
See step 5 :: https://semaphoreci.com/blog/2016/12/13/lightweight-docker-images-in-5-steps.html

        # Xdebug.
        RUN pecl install xdebug
        RUN docker-php-ext-enable xdebug
        RUN sed -i '1 a xdebug.remote_autostart=true' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        RUN sed -i '1 a xdebug.remote_mode=req' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        RUN sed -i '1 a xdebug.remote_handler=dbgp' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        RUN sed -i '1 a xdebug.remote_connect_back=1 ' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        RUN sed -i '1 a xdebug.remote_port=9000' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        RUN sed -i '1 a xdebug.remote_host=127.0.0.1' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        RUN sed -i '1 a xdebug.remote_enable=1' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

        RUN php -r "opcache_reset();"

        # Contains the Mac hack to get the permissions to work for development.
        # Set user 1000 and group staff to www-data, enables write permission.
        # https://github.com/boot2docker/boot2docker/issues/581#issuecomment-114804894
        RUN usermod -u 1000 www-data
        RUN usermod -G staff www-data

        ### DEV SPECIFIC - END ###

Could be:

        # Xdebug.
        RUN pecl install xdebug && \
        docker-php-ext-enable xdebug && \
        sed -i '1 a xdebug.remote_autostart=true' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
        sed -i '1 a xdebug.remote_mode=req' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
        sed -i '1 a xdebug.remote_handler=dbgp' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
        sed -i '1 a xdebug.remote_connect_back=1 ' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
        sed -i '1 a xdebug.remote_port=9000' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
        sed -i '1 a xdebug.remote_host=127.0.0.1' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
        sed -i '1 a xdebug.remote_enable=1' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \

        php -r "opcache_reset();" && \

        # Contains the Mac hack to get the permissions to work for development.
        # Set user 1000 and group staff to www-data, enables write permission.
        # https://github.com/boot2docker/boot2docker/issues/581#issuecomment-114804894
        usermod -u 1000 www-data && \
        usermod -G staff www-data

        ### DEV SPECIFIC - END ###

**Comment by jaapjan** [comment]
Interesting, I think these changes make total sense. Tagging @NielsGG here as well. We are in the process of restructuring the GIT repos (and thus also the Docker images) a bit, see: https://github.com/goalgorilla/drupal_social/pull/305 

I think we should also verify all the Dockerfile's and implement the changes you are suggesting. Will try to review and merge Niels pullrequest sometime this week.

**Comment by NielsGG** [comment]
Thanks @spoetnik, Indeed I agree that the changes should be implemented to decrease the size of the image.

For reference: https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/
"You need to find the balance between readability (and thus long-term maintainability) of the Dockerfile and minimizing the number of layers it uses. Be strategic and cautious about the number of layers you use." 

In my opinion it does not hurt the readability much when we apply your implementation. I will create a PR with the changes for this new Docker repo that will replace the other implementation.
https://github.com/goalgorilla/open_social_docker

**Comment by ronaldtebrake** [comment]
Thanks spoetnik, I see it wasn't closed but updated anyway in: https://github.com/goalgorilla/open_social_docker/blob/master/dev/Dockerfile
