### ISSUE TITLE
Docker Install instructions - Reverse Proxy issue.

### ISSUE THREAD

**Issue by mikeohara-bsc** [goalgorilla/drupal_social#307]
Upon running the [Docker instructions for starting the dev environment](https://github.com/goalgorilla/drupal_social/wiki/Installing-and-updating), the proxy container is failing with "503 Service Temporarily Unavailable nginx/1.11.6" when run with Docker for Mac. I followed the docker instructions exactly minus the docker-machine components as Docker machine is not present with Docker for Mac. 

Zero issues when building, no errors. 

**Specifics**
- Mac OSX: Sierra 10.12.2
- Docker For Mac: 1.13.0-rc3-beta33.1
- Project build: Latest.

**Comment by NielsGG** [comment]
Hi @mikeohara-bsc,

Thanks for trying out Open Social. I had the same problem with the proxy container once and it was fixed when pulling the latest version.

`docker stop proxy`
`docker rm proxy`
`docker pull jwilder/nginx-proxy`
`docker run -d -p 80:80 --name=proxy -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy`

There could also be an error in your `/etc/hosts` file. You can try to access the container directly using the assigned port which you can see with `docker ps` to make sure it is an issue of the proxy container.

**Comment by mikeohara-bsc** [comment]
Ah. That was what it was. My /etc/hosts file was mucked up. Correcting that and it started working. Thank you!
