### ISSUE TITLE
Credentials for open social admin account

### ISSUE THREAD

**Issue by johnreytanquinco** [goalgorilla/drupal_social#310]
I have installed Open Social in Openshift. I'm not sure if I was given a random password with my admin account during the installation.

Is there any chance that I can retrieve the account, knowing that I don't have Drush command on the server?

Or can we request for drush to be included in the git repo?

**Comment by NielsGG** [comment]
Hi @johnreytanquinco,

If you know the email of the admin account you could try to retrieve a one time login link with the forgot password feature. /user/password.

Note that we do not use the GitHub issue queue actively. For future issues please use the issue queue on drupal.org.
https://www.drupal.org/project/issues/social?categories=All

It seems Drush is not included in the social template but you could easily add it yourself. For example see the development composer.json file.

https://github.com/goalgorilla/drupal_social/blob/master/composer.json

**Comment by johnreytanquinco** [comment]
Thanks @NielsGG . Noted
