### ISSUE TITLE
Compile sass files

### ISSUE THREAD

**Issue by gilleon** [goalgorilla/drupal_social#312]
Hi there,

Is there a standard procedure for compiling sass files for a subtheme base off socialbase?

**Comment by peterpolman** [comment]
We use Gulp for this. You can copy package.json (containing the modules), gulpfile.js (containing the tasks) and the components folder structure (containing the scss) to set up something similar in your custom sub theme. Run `npm install` to install the dependencies and `gulp watch` to fire the watch task.

Here you can find some extra information on the component library for Open Social that we have set up: http://styleguide.getopensocial.com/

Feel free to ask for support in our [issue queue](https://www.drupal.org/project/issues/social?categories=All).
