### ISSUE TITLE
Not able to edit path in default and custom views once create.

### ISSUE THREAD

**Issue by esafwan** [goalgorilla/drupal_social#315]
**OpenSocial Version:** 8.x-1.0-rc5
**Core Version:** Drupal 8.3.2

Path for a view only being able to be set at time of creating a view. After that, there is no way to change the path of an OpenSocial default view or custom view created post installation. When saving new path after editing the existing one, it gives an error `Path is empty.`

No error is logged in the error log. This issue doesn't exist in default Drupal 8 of the same version.

**Comment by jochemvn** [comment]
Hi @esafwan,
Please check out [this page](https://github.com/goalgorilla/drupal_social/wiki/!Support) on how we support our distribution. Please use the Drupal.org issue queue for creating issues.

**Comment by esafwan** [comment]
Sorry about that. I have posted the issue there.

**Comment by jochemvn** [comment]
No problem. Closing this issue here
