### ISSUE TITLE
Internal page cache and Internal dynamic page cache disabled by default

### ISSUE THREAD

**Issue by oriole9g** [goalgorilla/drupal_social#325]
When install Open Social profile Internal page cache and Internal dynamic page cache is disabled by default.

Why? Drupal standard profile enables page cache by default. Disable it's only useful when you use Memcache or external caches, and most sites do not use.

**Comment by ronaldtebrake** [comment]
As you can see this repository is aimed for developers working on the Open Social distribution. For usage on production we do advice to enable the caches. But for development & debugging purposes we disable it by default, enabling it shouldn't be too much of a hassle either.
