### ISSUE TITLE
Installation fails with "Drupal is already installed" translated in the chosen language.

### ISSUE THREAD

**Issue by markaspot** [goalgorilla/drupal_social#326]
I want to reference [this issue](https://github.com/markaspot/mark-a-spot/issues/59). I confirmed this behavior by installing Open Social at platform.sh. Could be interesting for you, too.

**Comment by ronaldtebrake** [comment]
Thanks for the reference!! Greatly appreciated. 
We've added a reference to your core issue here: https://www.drupal.org/project/social/issues/2832103

Hopefully this helps others as well
