### ISSUE TITLE
web docker won't start if blackfire credentials are not set

### ISSUE THREAD

**Issue by Kingdutch** [goalgorilla/drupal_social#336]
The newly added (#335) blackfire container can't start if it doesn't have any server credentials. 

If the blackfire container can't start then docker will prevent the web container from starting as well.

**Comment by bramtenhove** [comment]
Should I revert your PR? As in possibly a lot of cases we will not have any server credentials.

**Comment by Kingdutch** [comment]
@bramtenhove Could we copy it to a docker-compose-blackfire.yml ? Then only revert the original docker-compose.yml so it works as before? Also ensuring that the -ci file doesn’t include Blackfire.

This keeps the Blackfire functionality close at hand for those who want it :)

**Comment by truls1502** [comment]
I have created a suggestion PR #338 where I am agreed with @Kingdutch 

I hope it helps. 😊

**Comment by ronaldtebrake** [comment]
Thanks guys, PR is merged will go from there :D
