### ISSUE TITLE
Provide `docker-compose` alternative

### ISSUE THREAD

**Issue by pendashteh** [goalgorilla/drupal_social#384]
Installation guide uses `docker compose` and there is no mention to `docker-compose`.

Since `docker compose` is not necessarily available in each machine, in the case that the installation runs with `docker-compose` as well as `docker compose`, it is worth to be mentioned.

Otherwise, this will potentially block the steps a user is taking in setting up their Open Social instance.

**Comment by Kingdutch** [comment]
As explained in https://github.com/goalgorilla/drupal_social/pull/383#issuecomment-1250073901 this will not be changed.

> Otherwise, this will potentially block the steps a user is taking in setting up their Open Social instance.

Please note that the `drupal_social` repository is meant for **development only** and should not be used in production.

**Comment by Kingdutch** [comment]
As explained in https://github.com/goalgorilla/drupal_social/pull/383#issuecomment-1250073901 this will not be changed.

> Otherwise, this will potentially block the steps a user is taking in setting up their Open Social instance.

Please note that the `drupal_social` repository is meant for **development only** and should not be used in production.
